apiVersion: v1
kind: ServiceAccount 
metadata:
  name: infrastructure-app-service-account 
--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata: 
  name: service-account-role 
  namespace: app-namespace 
subjects:
  groups: [] 
  
--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding 
metadata: 
  name: service-account-role-binding 
  namespace: app-namespace 
roleRef:
  - name: service-account-role 
    namespace: app-namespace 
subjects:
  user:
    type: ServiceAccount 
    name: infrastructure-app-service-account 
    namespace: app-namespace 